name: Publish to Azure Artifacts

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  PublishToAzureArtifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'

      - name: Get version from build.gradle
        id: get_version
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          VERSION=$(grep "version =" build.gradle | awk -F"'" '{print $2}')
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Set Release Version
        # This step sets the RELEASE_VERSION environment variable for the job.
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "RELEASE_VERSION=${{ github.sha }}" >> $GITHUB_ENV
          elif [ "${{ github.event_name }}" = "push" ]; then
            echo "RELEASE_VERSION=${{ steps.get_version.outputs.VERSION }}" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Publish to Azure DevOps Artifacts
        run: |
          ./gradlew publish
        env:
          AZURE_DEVOPS_ARTIFACT_USERNAME: ${{ secrets.AZURE_DEVOPS_ARTIFACT_USERNAME }}
          AZURE_DEVOPS_ARTIFACT_TOKEN: ${{ secrets.AZURE_DEVOPS_ARTIFACT_TOKEN }}
          # The RELEASE_VERSION is automatically picked up from the environment variable set in the previous step.
        shell: bash