name: Publish to Azure Artifacts

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

# Grant permissions for creating and pushing tags
permissions:
  contents: write

jobs:
  PublishToAzureArtifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0 # Need full history for tags

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'

      - name: Set Release Version
        # This step sets the RELEASE_VERSION environment variable for the job.
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            RELEASE_VERSION=${{ github.sha }}
          elif [ "${{ github.event_name }}" = "push" ]; then
            LATEST_TAG=$(git describe --tags --abbrev=0 --match '4.2.*')
            NEXT_PATCH=$(echo "$LATEST_TAG" | awk -F. '{ print $3+1 }')
            NEXT_VERSION="4.2.${NEXT_PATCH}"
  
            # Set the calculated version as a step output
            echo "next_version=$NEXT_VERSION" >> $GITHUB_OUTPUT
  
            git tag "$NEXT_VERSION"
            git push origin "$NEXT_VERSION"
            RELEASE_VERSION="$NEXT_VERSION"
          fi
        shell: bash

      - name: Publish to Azure DevOps Artifacts
        run: |
          ./gradlew publish
        env:
          AZURE_DEVOPS_ARTIFACT_USERNAME: ${{ secrets.AZURE_DEVOPS_ARTIFACT_USERNAME }}
          AZURE_DEVOPS_ARTIFACT_TOKEN: ${{ secrets.AZURE_DEVOPS_ARTIFACT_TOKEN }}
          RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
        shell: bash